feat: update to latest dependencies
mParticle/smartype pull request #30
Opened 2022-03-17 20:32 UTC by willpassidomo

(Draft to test CI checks with passing tests)

# Summary

Primary Changes:
- update KMP, Kotlin dependency -> 1.6.10
- update AGP -> 7.1.2
- update Gradle -> 7.3.2
- update kotlinx.serialization -> 1.3.2 (latest)

Secondary Changes
- `@JSExport` is no longer allowed in common modules as of Kotlin 1.5, so I had to spread `Serializable.kt` and `MessageReceiver.kt` files from common into their individual platform directories and add the annotation in the `jsMain` package
- `configuration = jvmDefault` was removed, we used this to pull in the jvm build from a multiplatform module into a pure-java module, multiplatform plugin is now smart enough to do that on it's own
- Carthage cinterops broke with one of these changes, I replaced the manual configuration we did with the `native.cocoapods` plugin..much more modern and easy to configure. I also added the neccessary CI steps to pull in the required env dependencies
- update AGP fields in the `android { }` closure to avoid using methods deprecated in AGP 7x...`targetSdkVersion` -> `targetSdk` for example

## Master Issue
- Closes https://go.mparticle.com/work/SQDSDKS-3485

2022-03-18 18:26 UTC, willpassidomo commented
sorry for tagging everyone! I figured all of you might have something add or want to see this, but feel free to leave the final approval to Michael or Brandon...I tested this fairly thoroughly and I'm confident it's functional :)

2022-03-18 21:28 UTC, samdozor requested changes
I thought the CI covered this...but it doesn't look like it actually does: have you tried building the sample iOS app with these changes? I remember having to jump through a ton of hoops to generate the framework correctly such that it could be imported into a project. 

It looks like CI right now is running smartype for the ios example, but it's not then building the ios example. my ask is that we manually test this PR to make sure that still works (if we can't add a build step to CI)

2022-03-21 14:26 UTC, willpassidomo commented
@samdozor so, this problem interestingly enough only occurs when you build either iOS or Android AND Web. CI didn't catch this since we build each on separately. [This logic](https://github.com/mParticle/smartype/blob/7808bd61aaa10519c54154f33fedbd32a077bb3f/smartype-generator/src/main/kotlin/com/mparticle/smartype/generator/Generator.kt#L99-L119) is writing two identical files (with identical/duplicate name spaces) into the same source set and causing a Duplicate Class Exception in the `generate` step

I'm still looking about what changed with this upgrade, since I know this worked before, but the step seems unnecessary now

2022-03-21 18:31 UTC, mchuangatmp approved these changes
let's turn on aborting for lint errors in a future PR

2022-03-23 20:46 UTC, merged